name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"   # t√§glich 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          # Look
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Europe/Berlin

          # Activity / basics
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5

          # Languages
          plugin_languages: no


          # Repos
          repositories_forks: no
